-- Priest Rediance spellbook specialization and Inner Fervor passive.
-- IDs owned by this migration:
-- - SkillLine: 9003 (Rediance)
-- - SkillLineAbility: 900200 (Inner Fervor only; Fervor is a technical aura)
-- - Spell: 900201 (Inner Fervor), 900202-900206 (Fervor stack auras)
-- - Client SpellIcon.dbc: 90020 (Rediance), 90021 (Fervor)
--
-- This migration clones existing DBC rows from the live DBC mirrors so it stays
-- compatible with the server's exact column set. It requires populated DBC
-- mirror tables.

SET @SKILLLINE_REDIANCE := 9003;
SET @SPELL_INNER_FERVOR := 900201;
SET @SPELL_FERVOR_AURA_FIRST := 900202;
SET @SPELL_FERVOR_AURA_LAST := 900206;
SET @SPELLICON_REDIANCE := 90020;
SET @SPELLICON_FERVOR := 90021;
SET @SKILLLINEABILITY_INNER_FERVOR := 900200;
SET @PRIEST_CLASSMASK := 16;
SET @ALL_RACES_MASK := 0;

DELETE FROM playercreateinfo_spell_custom WHERE `Spell` IN (@SPELL_INNER_FERVOR);
DELETE FROM skilllineability_dbc WHERE `ID` IN (@SKILLLINEABILITY_INNER_FERVOR, 900201) OR `Spell` = @SPELL_INNER_FERVOR OR `Spell` BETWEEN @SPELL_FERVOR_AURA_FIRST AND @SPELL_FERVOR_AURA_LAST;
DELETE FROM spell_dbc WHERE `ID` = @SPELL_INNER_FERVOR OR `ID` BETWEEN @SPELL_FERVOR_AURA_FIRST AND @SPELL_FERVOR_AURA_LAST;
DELETE FROM skillline_dbc WHERE `ID` = @SKILLLINE_REDIANCE;

CREATE TEMPORARY TABLE tmp_rediance_skillline LIKE skillline_dbc;
INSERT INTO tmp_rediance_skillline SELECT * FROM skillline_dbc WHERE `ID` = 56 LIMIT 1;
UPDATE tmp_rediance_skillline
SET `ID` = @SKILLLINE_REDIANCE,
    `CategoryID` = 7,
    `DisplayName_Lang_enUS` = 'Rediance',
    `DisplayName_Lang_enGB` = 'Rediance',
    `DisplayName_Lang_itIT` = 'Rediance',
    `DisplayName_Lang_Mask` = 16712190,
    `Description_Lang_enUS` = 'Priest Rediance specialization.',
    `Description_Lang_enGB` = 'Priest Rediance specialization.',
    `Description_Lang_itIT` = 'Specializzazione Rediance del prete.',
    `Description_Lang_Mask` = 16712190,
    `SpellIconID` = @SPELLICON_REDIANCE,
    `CanLink` = 0;
INSERT INTO skillline_dbc SELECT * FROM tmp_rediance_skillline;
DROP TEMPORARY TABLE tmp_rediance_skillline;

CREATE TEMPORARY TABLE tmp_rediance_spell LIKE spell_dbc;
INSERT INTO tmp_rediance_spell SELECT * FROM spell_dbc WHERE `ID` = 14752 LIMIT 1;
UPDATE tmp_rediance_spell
SET `ID` = @SPELL_INNER_FERVOR,
    `Attributes` = ((`Attributes` | 64) & ~128),
    `DurationIndex` = 0,
    `CumulativeAura` = 0,
    `Effect_1` = 0,
    `Effect_2` = 0,
    `Effect_3` = 0,
    `EffectAura_1` = 0,
    `EffectAura_2` = 0,
    `EffectAura_3` = 0,
    `EffectBasePoints_1` = 0,
    `EffectBasePoints_2` = 0,
    `EffectBasePoints_3` = 0,
    `SpellIconID` = @SPELLICON_FERVOR,
    `ActiveIconID` = @SPELLICON_FERVOR,
    `Name_Lang_enUS` = 'Inner Fervor',
    `Name_Lang_enGB` = 'Inner Fervor',
    `Name_Lang_itIT` = 'Inner Fervor',
    `Name_Lang_Mask` = 16712190,
    `NameSubtext_Lang_enUS` = '',
    `NameSubtext_Lang_enGB` = '',
    `NameSubtext_Lang_itIT` = '',
    `Description_Lang_enUS` = 'Your Rediance spells build Fervor, up to 5 stacks. After 6 sec without generating or consuming Fervor, 1 stack is lost.',
    `Description_Lang_enGB` = 'Your Rediance spells build Fervor, up to 5 stacks. After 6 sec without generating or consuming Fervor, 1 stack is lost.',
    `Description_Lang_itIT` = 'Le tue magie Rediance accumulano Fervor, fino a 5 cariche. Dopo 6 sec senza generare o consumare Fervor, perdi 1 carica.',
    `Description_Lang_Mask` = 16712190,
    `AuraDescription_Lang_enUS` = 'Fervor is generated by Flame of Judgment and Mark of Sin, and consumed by Divine Judgment.',
    `AuraDescription_Lang_enGB` = 'Fervor is generated by Flame of Judgment and Mark of Sin, and consumed by Divine Judgment.',
    `AuraDescription_Lang_itIT` = 'Fervor viene generato da Flame of Judgment e Mark of Sin, e consumato da Divine Judgment.',
    `AuraDescription_Lang_Mask` = 16712190,
    `SpellClassSet` = 6,
    `DefenseType` = 0,
    `PreventionType` = 0,
    `SchoolMask` = 2;
INSERT INTO spell_dbc SELECT * FROM tmp_rediance_spell;
TRUNCATE TABLE tmp_rediance_spell;

INSERT INTO tmp_rediance_spell SELECT * FROM spell_dbc WHERE `ID` = 14752 LIMIT 1;
UPDATE tmp_rediance_spell
SET `ID` = @SPELL_FERVOR_AURA_FIRST,
    `Attributes` = (`Attributes` & ~128 & ~64),
    `DurationIndex` = 32,
    `CumulativeAura` = 5,
    `Effect_1` = 6,
    `Effect_2` = 0,
    `Effect_3` = 0,
    `EffectAura_1` = 4,
    `EffectAura_2` = 0,
    `EffectAura_3` = 0,
    `ImplicitTargetA_1` = 1,
    `EffectBasePoints_1` = 0,
    `EffectBasePoints_2` = 0,
    `EffectBasePoints_3` = 0,
    `SpellIconID` = @SPELLICON_FERVOR,
    `ActiveIconID` = @SPELLICON_FERVOR,
    `Name_Lang_enUS` = 'Fervor',
    `Name_Lang_enGB` = 'Fervor',
    `Name_Lang_itIT` = 'Fervor',
    `Name_Lang_Mask` = 16712190,
    `NameSubtext_Lang_enUS` = '',
    `NameSubtext_Lang_enGB` = '',
    `NameSubtext_Lang_itIT` = '',
    `Description_Lang_enUS` = 'Damage taken +0%.',
    `Description_Lang_enGB` = 'Damage taken +0%.',
    `Description_Lang_itIT` = 'Danni subiti +0%.',
    `Description_Lang_Mask` = 16712190,
    `AuraDescription_Lang_enUS` = 'Damage taken +0%.',
    `AuraDescription_Lang_enGB` = 'Damage taken +0%.',
    `AuraDescription_Lang_itIT` = 'Danni subiti +0%.',
    `AuraDescription_Lang_Mask` = 16712190,
    `SpellClassSet` = 6,
    `DefenseType` = 0,
    `PreventionType` = 0,
    `SchoolMask` = 2;
INSERT INTO spell_dbc SELECT * FROM tmp_rediance_spell;
DROP TEMPORARY TABLE tmp_rediance_spell;

CREATE TEMPORARY TABLE tmp_rediance_skilllineability LIKE skilllineability_dbc;
INSERT INTO tmp_rediance_skilllineability SELECT * FROM skilllineability_dbc WHERE `Spell` = 588 LIMIT 1;
UPDATE tmp_rediance_skilllineability
SET `ID` = @SKILLLINEABILITY_INNER_FERVOR,
    `SkillLine` = @SKILLLINE_REDIANCE,
    `Spell` = @SPELL_INNER_FERVOR,
    `RaceMask` = @ALL_RACES_MASK,
    `ClassMask` = @PRIEST_CLASSMASK,
    `ExcludeRace` = 0,
    `ExcludeClass` = 0,
    `MinSkillLineRank` = 0,
    `SupercededBySpell` = 0,
    `AcquireMethod` = 0,
    `TrivialSkillLineRankHigh` = 0,
    `TrivialSkillLineRankLow` = 0,
    `CharacterPoints_1` = 0,
    `CharacterPoints_2` = 0;
INSERT INTO skilllineability_dbc SELECT * FROM tmp_rediance_skilllineability;
DROP TEMPORARY TABLE tmp_rediance_skilllineability;

INSERT INTO playercreateinfo_spell_custom (`racemask`, `classmask`, `Spell`, `Note`)
VALUES (@ALL_RACES_MASK, @PRIEST_CLASSMASK, @SPELL_INNER_FERVOR, 'Priest Rediance - Inner Fervor');
