-- Priest Rediance trainer spell: Radiant Strike.
-- Spell.dbc/client MPQ rows are generated by tools/build_reborn_client_patch.py.
-- Trainer IDs 11 and 12 are the stock priest trainer groups in this core.

SET @PRIEST_TRAINER_1 := 11;
SET @PRIEST_TRAINER_2 := 12;

DELETE FROM `trainer_spell`
WHERE `TrainerId` IN (@PRIEST_TRAINER_1, @PRIEST_TRAINER_2)
  AND `SpellId` BETWEEN 900260 AND 900267;

INSERT INTO `trainer_spell`
(`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(@PRIEST_TRAINER_1, 900260, 18000, 0, 0, 0, 0, 0, 24, 0),
(@PRIEST_TRAINER_2, 900260, 18000, 0, 0, 0, 0, 0, 24, 0),
(@PRIEST_TRAINER_1, 900261, 80000, 0, 0, 900260, 0, 0, 32, 0),
(@PRIEST_TRAINER_2, 900261, 80000, 0, 0, 900260, 0, 0, 32, 0),
(@PRIEST_TRAINER_1, 900262, 200000, 0, 0, 900261, 0, 0, 40, 0),
(@PRIEST_TRAINER_2, 900262, 200000, 0, 0, 900261, 0, 0, 40, 0),
(@PRIEST_TRAINER_1, 900263, 420000, 0, 0, 900262, 0, 0, 48, 0),
(@PRIEST_TRAINER_2, 900263, 420000, 0, 0, 900262, 0, 0, 48, 0),
(@PRIEST_TRAINER_1, 900264, 850000, 0, 0, 900263, 0, 0, 56, 0),
(@PRIEST_TRAINER_2, 900264, 850000, 0, 0, 900263, 0, 0, 56, 0),
(@PRIEST_TRAINER_1, 900265, 1350000, 0, 0, 900264, 0, 0, 64, 0),
(@PRIEST_TRAINER_2, 900265, 1350000, 0, 0, 900264, 0, 0, 64, 0),
(@PRIEST_TRAINER_1, 900266, 1800000, 0, 0, 900265, 0, 0, 72, 0),
(@PRIEST_TRAINER_2, 900266, 1800000, 0, 0, 900265, 0, 0, 72, 0),
(@PRIEST_TRAINER_1, 900267, 2200000, 0, 0, 900266, 0, 0, 80, 0),
(@PRIEST_TRAINER_2, 900267, 2200000, 0, 0, 900266, 0, 0, 80, 0);
