-- Priest Rediance trainer spell: Step of Light.
-- Spell.dbc/client MPQ rows are generated by tools/build_reborn_client_patch.py.
-- Trainer IDs 11 and 12 are the stock priest trainer groups in this core.

SET @PRIEST_TRAINER_1 := 11;
SET @PRIEST_TRAINER_2 := 12;

DELETE FROM `trainer_spell`
WHERE `TrainerId` IN (@PRIEST_TRAINER_1, @PRIEST_TRAINER_2)
  AND `SpellId` BETWEEN 900280 AND 900282;

INSERT INTO `trainer_spell`
(`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(@PRIEST_TRAINER_1, 900280, 100000, 0, 0, 0, 0, 0, 34, 0),
(@PRIEST_TRAINER_2, 900280, 100000, 0, 0, 0, 0, 0, 34, 0),
(@PRIEST_TRAINER_1, 900281, 750000, 0, 0, 900280, 0, 0, 54, 0),
(@PRIEST_TRAINER_2, 900281, 750000, 0, 0, 900280, 0, 0, 54, 0),
(@PRIEST_TRAINER_1, 900282, 1950000, 0, 0, 900281, 0, 0, 74, 0),
(@PRIEST_TRAINER_2, 900282, 1950000, 0, 0, 900281, 0, 0, 74, 0);
