-- Priest Rediance trainer spell: Holy Chastisement.
-- Spell.dbc/client MPQ rows are generated by tools/build_reborn_client_patch.py.
-- Trainer IDs 11 and 12 are the stock priest trainer groups in this core.

SET @PRIEST_TRAINER_1 := 11;
SET @PRIEST_TRAINER_2 := 12;

DELETE FROM `trainer_spell`
WHERE `TrainerId` IN (@PRIEST_TRAINER_1, @PRIEST_TRAINER_2)
  AND `SpellId` BETWEEN 900270 AND 900273;

INSERT INTO `trainer_spell`
(`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(@PRIEST_TRAINER_1, 900270, 50000, 0, 0, 0, 0, 0, 30, 0),
(@PRIEST_TRAINER_2, 900270, 50000, 0, 0, 0, 0, 0, 30, 0),
(@PRIEST_TRAINER_1, 900271, 360000, 0, 0, 900270, 0, 0, 46, 0),
(@PRIEST_TRAINER_2, 900271, 360000, 0, 0, 900270, 0, 0, 46, 0),
(@PRIEST_TRAINER_1, 900272, 1250000, 0, 0, 900271, 0, 0, 62, 0),
(@PRIEST_TRAINER_2, 900272, 1250000, 0, 0, 900271, 0, 0, 62, 0),
(@PRIEST_TRAINER_1, 900273, 2150000, 0, 0, 900272, 0, 0, 78, 0),
(@PRIEST_TRAINER_2, 900273, 2150000, 0, 0, 900272, 0, 0, 78, 0);
