-- Priest Rediance trainer spell: Burning Shield.
-- Spell.dbc/client MPQ rows are generated by tools/build_reborn_client_patch.py.
-- Trainer IDs 11 and 12 are the stock priest trainer groups in this core.

SET @PRIEST_TRAINER_1 := 11;
SET @PRIEST_TRAINER_2 := 12;

DELETE FROM `trainer_spell`
WHERE `TrainerId` IN (@PRIEST_TRAINER_1, @PRIEST_TRAINER_2)
  AND `SpellId` BETWEEN 900310 AND 900313;

INSERT INTO `trainer_spell`
(`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(@PRIEST_TRAINER_1, 900310, 320000, 0, 0, 0, 0, 0, 44, 0),
(@PRIEST_TRAINER_2, 900310, 320000, 0, 0, 0, 0, 0, 44, 0),
(@PRIEST_TRAINER_1, 900311, 850000, 0, 0, 900310, 0, 0, 56, 0),
(@PRIEST_TRAINER_2, 900311, 850000, 0, 0, 900310, 0, 0, 56, 0),
(@PRIEST_TRAINER_1, 900312, 1550000, 0, 0, 900311, 0, 0, 68, 0),
(@PRIEST_TRAINER_2, 900312, 1550000, 0, 0, 900311, 0, 0, 68, 0),
(@PRIEST_TRAINER_1, 900313, 2200000, 0, 0, 900312, 0, 0, 80, 0),
(@PRIEST_TRAINER_2, 900313, 2200000, 0, 0, 900312, 0, 0, 80, 0);
