-- Priest Rediance trainer spell: Purifying Glare.
-- Spell.dbc/client MPQ rows are generated by tools/build_reborn_client_patch.py.
-- Trainer IDs 11 and 12 are the stock priest trainer groups in this core.

SET @PRIEST_TRAINER_1 := 11;
SET @PRIEST_TRAINER_2 := 12;

DELETE FROM `trainer_spell`
WHERE `TrainerId` IN (@PRIEST_TRAINER_1, @PRIEST_TRAINER_2)
  AND `SpellId` BETWEEN 900300 AND 900303;

INSERT INTO `trainer_spell`
(`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(@PRIEST_TRAINER_1, 900300, 280000, 0, 0, 0, 0, 0, 42, 0),
(@PRIEST_TRAINER_2, 900300, 280000, 0, 0, 0, 0, 0, 42, 0),
(@PRIEST_TRAINER_1, 900301, 750000, 0, 0, 900300, 0, 0, 54, 0),
(@PRIEST_TRAINER_2, 900301, 750000, 0, 0, 900300, 0, 0, 54, 0),
(@PRIEST_TRAINER_1, 900302, 1450000, 0, 0, 900301, 0, 0, 66, 0),
(@PRIEST_TRAINER_2, 900302, 1450000, 0, 0, 900301, 0, 0, 66, 0),
(@PRIEST_TRAINER_1, 900303, 2150000, 0, 0, 900302, 0, 0, 78, 0),
(@PRIEST_TRAINER_2, 900303, 2150000, 0, 0, 900302, 0, 0, 78, 0);
