-- Priest Rediance trainer spell: Divine Judgment.
-- Spell.dbc/client MPQ rows are generated by tools/build_reborn_client_patch.py.
-- Trainer IDs 11 and 12 are the stock priest trainer groups in this core.

SET @PRIEST_TRAINER_1 := 11;
SET @PRIEST_TRAINER_2 := 12;

DELETE FROM `trainer_spell`
WHERE `TrainerId` IN (@PRIEST_TRAINER_1, @PRIEST_TRAINER_2)
  AND `SpellId` BETWEEN 900250 AND 900256;

INSERT INTO `trainer_spell`
(`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(@PRIEST_TRAINER_1, 900250, 9000, 0, 0, 0, 0, 0, 20, 0),
(@PRIEST_TRAINER_2, 900250, 9000, 0, 0, 0, 0, 0, 20, 0),
(@PRIEST_TRAINER_1, 900251, 50000, 0, 0, 900250, 0, 0, 30, 0),
(@PRIEST_TRAINER_2, 900251, 50000, 0, 0, 900250, 0, 0, 30, 0),
(@PRIEST_TRAINER_1, 900252, 200000, 0, 0, 900251, 0, 0, 40, 0),
(@PRIEST_TRAINER_2, 900252, 200000, 0, 0, 900251, 0, 0, 40, 0),
(@PRIEST_TRAINER_1, 900253, 500000, 0, 0, 900252, 0, 0, 50, 0),
(@PRIEST_TRAINER_2, 900253, 500000, 0, 0, 900252, 0, 0, 50, 0),
(@PRIEST_TRAINER_1, 900254, 1100000, 0, 0, 900253, 0, 0, 60, 0),
(@PRIEST_TRAINER_2, 900254, 1100000, 0, 0, 900253, 0, 0, 60, 0),
(@PRIEST_TRAINER_1, 900255, 1700000, 0, 0, 900254, 0, 0, 70, 0),
(@PRIEST_TRAINER_2, 900255, 1700000, 0, 0, 900254, 0, 0, 70, 0),
(@PRIEST_TRAINER_1, 900256, 2200000, 0, 0, 900255, 0, 0, 80, 0),
(@PRIEST_TRAINER_2, 900256, 2200000, 0, 0, 900255, 0, 0, 80, 0);
