-- Priest Rediance trainer spell: Judge's Gaze.
-- Spell.dbc/client MPQ rows are generated by tools/build_reborn_client_patch.py.
-- Trainer IDs 11 and 12 are the stock priest trainer groups in this core.

SET @PRIEST_TRAINER_1 := 11;
SET @PRIEST_TRAINER_2 := 12;

DELETE FROM `trainer_spell`
WHERE `TrainerId` IN (@PRIEST_TRAINER_1, @PRIEST_TRAINER_2)
  AND `SpellId` BETWEEN 900290 AND 900292;

INSERT INTO `trainer_spell`
(`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(@PRIEST_TRAINER_1, 900290, 160000, 0, 0, 0, 0, 0, 38, 0),
(@PRIEST_TRAINER_2, 900290, 160000, 0, 0, 0, 0, 0, 38, 0),
(@PRIEST_TRAINER_1, 900291, 850000, 0, 0, 900290, 0, 0, 56, 0),
(@PRIEST_TRAINER_2, 900291, 850000, 0, 0, 900290, 0, 0, 56, 0),
(@PRIEST_TRAINER_1, 900292, 1950000, 0, 0, 900291, 0, 0, 74, 0),
(@PRIEST_TRAINER_2, 900292, 1950000, 0, 0, 900291, 0, 0, 74, 0);
